# Tekijä: Akseli  Leino
# Muokkaaja: Sanni Sinisalo

structures:
  PTV: 0
  Heart: 1
  Ipsilateral lung: 2
  Contralateral lung: 3
  Contralateral breast: 4
  LAD: 5
  Ipsilateral humerus head: 6
  Brachial plexus: 7
  Esophagus: 8
  Trachea: 9
  Thyroid: 11

data_paths:
  VN0_data: "C:/Users/User01/GRADU/Aineisto/VN0ds/*/"
  VN+_data: "C:/Users/User01/GRADU/Aineisto/VN+ds/*/"
  ON0_data: "C:/Users/User01/GRADU/Aineisto/ON0ds/*/"
  ON+_data: "C:/Users/User01/GRADU/Aineisto/ON+ds/*/"

train_loader_config:
  samples_per_volume: 1
  max_length: 2000
  num_workers: 8
  
default: &DEFAULT
  gradient_accumulation: 1
  batch_size: 8
  patch_size: !!python/tuple [256, 256, 1]
  early_stopping_patience: 10
  in_channels: 3
  out_channels: 1
  filters: [64, 128, 256, 512, 1024]
  conv_layers: 2
  kernel_size: 3
  pool_size: 2
  skip_filters: 64
  act_func: "ReLU" # Match with torch.nn activation function classes
  EPOCHS: 20
  warmup_period: 4 # NOTE: This should always be gradient_accumulation*integer, otherwise it messes up lr scheduling
  warm_restart_every: 12 # NOTE: This should always be gradient_accumulation*integer
  optimizer:
    type: "SGD" # Match with torch.optim objects
    params:
      lr: 0.01
    momentum: 0.9
    nesterov: !!python/bool True
  primary_loss: "MSELoss" # Match losses with torch.nn loss classes
  secondary_loss: "L1Loss" # This is used only as metric
  experiment_name: "Results 3/2026"

manual_search:
  - <<: *DEFAULT

grid_search:
  <<: *DEFAULT
  conv_layers:
    - 2
    - 1
  act_func:
    - "ReLU"
    - "SELU"
    - "CELU"

random_search:
  <<: *DEFAULT
  random_samples: 100
  batch_size:
    min: 1
    max: 8
  patch_size:
    - !!python/tuple [256, 256, 4]
    - !!python/tuple [256, 256, 8]
    - !!python/tuple [256, 256, 16]
    - !!python/tuple [128, 128, 16]
    - !!python/tuple [128, 128, 32]
  conv_layers:
    min: 1
    max: 3
  kernel_size:
    min: 2
    max: 4
  act_func: ['ReLU', 'LeakyReLU', 'CELU']
  optimizer:
    - type: "Adam"
      params:
        lr:
          min: 0.0000001
          max: 0.001
    - type: "AdamW"
      params:
        lr:
          min: 0.0000001
          max: 0.001
    - type: "SGD"
      params:
        lr:
          min: 0.0000001
          max: 0.001
